# 角色卡配置文件示例
# 使用方法: node build-card.js config.yaml

# 基础信息
name: 示例卡片
creator: ""
character_version: ""

# 主要字段映射(空字符串表示该字段为空)
fields:
  description: 作品/示例作品/角色设定.xyaml
  personality: ""
  scenario: ""
  first_mes: 作品/示例作品/开场白.md
  mes_example: ""
  creator_notes: ""
  system_prompt: ""
  post_history_instructions: ""

# 扩展字段
extensions:
  talkativeness: "0.5"
  fav: false
  world: 示例卡片

  # 状态栏文件路径(可选)
  status_bar: 作品/示例作品/状态栏.html

# 角色书配置
character_book:
  name: 示例卡片

  entries:
    # [InitVar]初始化条目 - 保持关闭状态
    - comment: "[InitVar]初始化"
      content: 作品/示例作品/变量初始化.xyaml
      enabled: false
      position: before_char
      insertion_order: 100
      depth: 4
      role: 0

    # 变量更新规则 - 永久、@D系统、深度1、顺序1
    - comment: "变量更新规则"
      content: 作品/示例作品/变量更新规则.xyaml
      enabled: true
      position: at_depth  # 对应 value=4
      insertion_order: 1
      depth: 1
      role: 0  # @D系统

    # 变量处理指令集 - 永久、@D系统、深度1、顺序2
    - comment: "变量处理指令集"
      content: 作品/示例作品/变量处理指令集.xyaml
      enabled: true
      position: at_depth
      insertion_order: 2
      depth: 1
      role: 0

    # 背景设定 - 永久、角色定义之前、顺序1
    - comment: "背景设定"
      content: 作品/示例作品/背景设定.xyaml
      enabled: true
      position: before_char
      insertion_order: 1
      depth: 4
      role: 0

    # 玩家角色 - 永久、角色定义之前、顺序2
    - comment: "玩家角色_{{user}}"
      content: 作品/示例作品/玩家角色.xyaml
      enabled: true
      position: before_char
      insertion_order: 2
      depth: 4
      role: 0

    # 其他设定条目 - 可以有多个,insertion_order依次递增
    - comment: "其他设定条目1"
      content: 作品/示例作品/其他设定1.xyaml
      enabled: true
      position: after_char
      insertion_order: 1
      depth: 4
      role: 0

    - comment: "其他设定条目2"
      content: 作品/示例作品/其他设定2.xyaml
      enabled: true
      position: after_char
      insertion_order: 2
      depth: 4
      role: 0
